
services:
  server:
    image: python
    command: tail -f
    volumes:
      - ./:/p
    ports:
      - 2223:2223
    networks:
      my_network:
        #ipv4_address: 192.168.10.20
  app1:
    image: python
    command: tail -f
    volumes:
      - ./:/p
    networks:
      my_network:
        #ipv4_address: 192.168.1.2

  app2:
    image: python
    command: tail -f
    volumes:
      - ./:/p
    networks:
      my_network:
        #ipv4_address: 192.168.1.2
          #  app2:
          #    image: nginx
          #    networks:
          #      my_network:
          #        ipv4_address: 192.168.1.3
          #
          #  app3:
          #    image: nginx
          #    networks:
          #      my_network:
          #        ipv4_address: 192.168.1.4

networks:
  my_network:
    driver: bridge
      #    ipam:
      #      config:
      #        - subnet: 192.168.1.0/24

